try:
	raise ValueError('A value error happened.')
except ValueError:
	print('ValueError in our code')
